### ISSUE TITLE
Import the current UI component using es6, the button click event appears to be disabled

### ISSUE THREAD

**Issue by JumpNote** [xense/phaser-ui-comps#1]
![image](https://user-images.githubusercontent.com/10766457/57681064-86facf00-7661-11e9-86b9-e0c42ab3d996.png)
This project makes a lot of sense and saves a lot of UI work

**Comment by JumpNote** [comment]
When the button and check box are clicked, the event does not respond, but the mouseover event appears to be valid

**Comment by xense** [comment]
@JumpNote please, show your code.

**Comment by JumpNote** [comment]
![image](https://user-images.githubusercontent.com/10766457/57692913-8d497500-767a-11e9-94ed-d9eabf698d8b.png)
as picture，I just changed the method exported by the phasercomps class

**Comment by JumpNote** [comment]
```
/**
 * @namespace PhaserComps
 */

import ComponentClip from "./clip/ComponentClip";
import UIComponents from "./components/UIComponents";
import Plugin from "./plugin/Plugin";
import UIManager from "./manager/UIManager";

var PhaserComps = {
	ComponentClip: ComponentClip,
	UIComponents: UIComponents,
	Plugin: Plugin,
	UIManager: UIManager
};
export default PhaserComps
```

**Comment by tong3d** [comment]
I have the same question

**Comment by xense** [comment]
PhaserComps object is available globally now, so you don't really need to import it. 
But I'll try to fix import problem soon.

**Comment by JumpNote** [comment]
I may have to use the import method because I'm using a build with the vue cli
